# This file was generated by GoReleaser. DO NOT EDIT.
cask "rdstail" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "7d9efbf39905a369e41631e798bdba123c9099f4ca6650090b5ae27560f78943"
      url "https://github.com/avinash-gupta-rdz/rdstail/releases/download/v#{version}/rdstail_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6351fec7a9fc036f960933e28f3c455f20c7af788102ff6aaf5e30bb9834409d"
      url "https://github.com/avinash-gupta-rdz/rdstail/releases/download/v#{version}/rdstail_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d72c8f57af7293afd162313a2a327f56a35c757f0fdaaf1e319b5a1256bb2548"
      url "https://github.com/avinash-gupta-rdz/rdstail/releases/download/v#{version}/rdstail_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cfc5bafe456559c80f5b7720d9dc3a43061acbc63dd9267b40ecccf5ae5f2635"
      url "https://github.com/avinash-gupta-rdz/rdstail/releases/download/v#{version}/rdstail_linux_amd64.tar.gz"
    end
  end

  name "rdstail"
  desc "Ship AWS RDS logs to S3, Kafka, or HTTP without CloudWatch"
  homepage "https://github.com/avinash-gupta-rdz/rdstail"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rdstail"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rdstail"]
    end
  end

  # No zap stanza required
end
