# This file was generated by GoReleaser. DO NOT EDIT.
cask "rdstail" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "d166ea4aa120377a323d7225f7bdbde4048022851a4b2b034a5a2308aefe2fa9"
      url "https://github.com/avinash-gupta-rdz/rdstail/releases/download/v#{version}/rdstail_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c7764f1b34e7f8a5af02391e2326385a1d7cab19fa0240c633e0c1f1807dcd62"
      url "https://github.com/avinash-gupta-rdz/rdstail/releases/download/v#{version}/rdstail_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d60e21b81640009d8258125e776f9c30e0a91e455d35f50fb7daba6910ffc30c"
      url "https://github.com/avinash-gupta-rdz/rdstail/releases/download/v#{version}/rdstail_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "031990ea3553575aa6cd35d628a6deca493e5d8b280cdadce02e3b4d372372b7"
      url "https://github.com/avinash-gupta-rdz/rdstail/releases/download/v#{version}/rdstail_linux_amd64.tar.gz"
    end
  end

  name "rdstail"
  desc "Ship AWS RDS logs to S3, Kafka, or HTTP without CloudWatch"
  homepage "https://github.com/avinash-gupta-rdz/rdstail"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rdstail"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rdstail"]
    end
  end

  # No zap stanza required
end
