# This file was generated by GoReleaser. DO NOT EDIT.
cask "rdstail" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "2ab1f3b5ee5549e058fe1c616f8f80ef69b84467d5f18d751e67ea0f9d875503"
      url "https://github.com/avinash-gupta-rdz/rdstail/releases/download/v#{version}/rdstail_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ce484c1e3a9d35fa0f5d1ff7c480fc3ec1d3b58d9d177a56cf58bb91d2f85de"
      url "https://github.com/avinash-gupta-rdz/rdstail/releases/download/v#{version}/rdstail_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ddc1a68583839d31b376dcf1c96040ed1a1ba3992247573bad83d88a2f45dbb6"
      url "https://github.com/avinash-gupta-rdz/rdstail/releases/download/v#{version}/rdstail_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "793ef561a777205f4913ff310003761dcc687be1a83fbad3cc232e947f081cf9"
      url "https://github.com/avinash-gupta-rdz/rdstail/releases/download/v#{version}/rdstail_linux_amd64.tar.gz"
    end
  end

  name "rdstail"
  desc "Ship AWS RDS logs to S3, Kafka, or HTTP without CloudWatch"
  homepage "https://github.com/avinash-gupta-rdz/rdstail"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rdstail"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rdstail"]
    end
  end

  # No zap stanza required
end
